config/routes.rb
Moerderspiel::Application.routes.draw do
  resources :rankings

  resources :users
  resources :games
  resources :sessions
  resources :password_resets

  get "login"   => "sessions#new",        :as => "login"
  get "logout"  => "sessions#destroy",    :as => "logout"
  get "signup"  => "users#new",           :as => "signup"
  get "gamemaster" => "games#gamemaster", :as => "gamemaster"
  get "participate/:id" => "games#participate", :as => "participate"
  get "ranking" => "rankings#index", :as => "user_ranking"
  get "kill/:id" => "games#kill", :as => "kill"
  get "start/:id" => "games#start", :as => "start_game"
  get "end/:id" => "games#end_game", :as => "end_game"

  root 'welcome#index'
  get 'welcome/show_game_by_name'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
     @user_games = Game.where(gamemaster_id: current_user).last(5)
    end
  end

  def show_game_by_name
    name = params[:name]
    game = Game.where(name: name).first
    if game
      redirect_to game
    else
      redirect_to root_path, :flash => { :error => "Das Spiel \"#{name}\" wurde nicht gefunden" }
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_user_games.html.haml
%h4 Aktuellsten Spiele

%table.table
  %thead
    %tr
      %th Spiel
  - @user_games.each do |game|
    %tr
      %td= link_to "#{game.name}", game

app/views/welcome/index.html.haml
.row-fluid
	.span6 
		%h3 Was ist das Mörderspiel?
		Das Mörderspiel ist ein Spiel was gut neben dem Alltag gespielt werden kann.
		In diesem Spiel geht es darum jemanden bestimmten zu finden und ihn, ohne Zeugen,
		umzubringen.
		%br
		Klingt brutal? Ist es aber nicht!
		%br
		Wie bereits gesagt handelt es sich um ein Spiel, bleibt also die Frage:
		%br
		Wie begeht man einen Mord?
		%ul
			%li Opfer ausfindig machen.
			%li Opfer ohne Zeugen einen Gegenstand überreichen.
			%li Dem Opfer mitteilen das es TOT ist.
		Die Probleme die man bei dem Spiel überwinden muss sind zum einen die Paranoia des Opfers
		und zum anderen den Zeitpunkt zu finden in den kein Zeuge dabei ist.
		
		Zeugen sind diejenigen die noch am Spiel beteiligt sind also noch ein Leben haben, und somit
		selbst noch einen Auftrag besitzen.
		
		%h4 Genaueres zu Aufträgen
		
		Man bekommt bei Spielbeginn eine Anzahl an Aufträgen die der Anzahl an Kreisen enstpricht.
		So erhält jeder Spieler in einer Runde in der zwei Kreise existieren zwei Aufträge.
		Die Kreise sind die Leben eines jeden Spielers. Alle Kreise laufen parralel und unabhängig
		voneinander.
		
		Auf jedem Auftrag steht das Opfer und auch das Ende der Runde also wann der Spielleiter die Runde
		beendet.
	.span6
		.row-fluid
			.span12
				%h3 Ein Spiel betrachten
				- if current_user && !@user_games.empty?
					= render "user_games"
				%br
				= form_tag(welcome_show_game_by_name_path, method: "get") do
					= label_tag(:name, "Spielname")
					= text_field_tag(:name)
					%br
					= submit_tag("Anzeigen")
		.row-fluid
			.span12
				- if current_user
					%h3 Ein neues Spiel erstellen
					Wenn du ein Spiel erstellst wirst du der Spielleiter sein.
					%h4 Der Spielleiter kann nicht am Spiel Teilnehmen.
					= link_to "Neues Spiel erstellen", new_game_path
				- else
					%h3 Warum registrieren?
					Einen Account beim Mörderspieltool zu haben hat mehrere Vorteile:
					%ul
						%li Spiele erstellen.
						%li keine Einwegpasswörter mehr nötig
						%li Punkte sammeln für die Mörder Rangliste
						%li seine Aufträge immer wieder anschauen
						%li sämmtliche Spiele betrachten können an den man teilgenommen hat
					Wenn du dich registrieren willst kannst du das 
					=link_to "hier", new_user_path