config/routes.rb
Moerderspiel::Application.routes.draw do
  resources :rankings

  resources :users
  resources :games
  resources :sessions
  resources :password_resets

  get "login"   => "sessions#new",        :as => "login"
  get "logout"  => "sessions#destroy",    :as => "logout"
  get "signup"  => "users#new",           :as => "signup"
  get "gamemaster" => "games#gamemaster", :as => "gamemaster"
  get "participate/:id" => "games#participate", :as => "participate"
  get "ranking" => "rankings#index", :as => "user_ranking"
  get "kill/:id" => "games#kill", :as => "kill"
  get "start/:id" => "games#start", :as => "start_game"
  get "end/:id" => "games#end_game", :as => "end_game"

  root 'welcome#index'
  get 'welcome/show_game_by_name'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :gamemaster, class_name: 'User'
  has_many :player
  has_many :circles
  has_many :extrajobs
  after_create :create_circles
  
  def circle_count
    @circle_count || 1
  end
  
  def circle_count=(circle_count)
    @circle_count = circle_count.to_i
  end
  
  def create_circles
    circle_count.times do |i|
      Circle.create number: (i+1),
                    game_id: self.id
    end
  end
  
  
  def participate(user=nil, name=nil, email=nil)
    if user.nil?
      if(Player.where(name: name, game: self).empty? &&
         Player.where(email: email, game: self).empty?)
         Player.create name: name,
                       email: email,
                       game: self
        return true
      else
        return false
      end
    else
      if(Player.where(user: user, game: self).empty?)
         Player.create user: user,
                       game: self
        return true
      else
        return false
      end
    end
  end
  
  def get_player_statistics
    "#{get_living_player.size}/#{self.player.size}"
  end
  
  def get_living_player
    players = []
    self.player.each do |player|
      if player.alive?
        players << player
      end
    end
    return players
  end
  
    
  def start
    players = self.player
    self.circles.each do |circle|
      play =players.shuffle 
      play.each_with_index do |player, i|
        if player==play.last
          Job.create killer: player,
                     victim: play.first,
                     circle: circle,
                     status: "unfinished",
                     key: Job.generate_key
        else
          Job.create killer: player,
                     victim: play[i+1],
                     circle: circle,
                     status: "unfinished",
                     key: Job.generate_key
        end
      end
    end
    self.update_attributes(status: "running")
  end
  
  def end_game
    jobs = Job.where(circle_id: self.circles, status: "unfinished")
    jobs.each do |job|
      job.update_attributes(status: "canceled")
    end
    self.update_attributes(status: "finished")
  end
  
  def finished_jobs
    Job.where(circle_id: self.circles, status: "done")
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @opengames = []
    @closedgames = []
    current_user.player.each do |player|
      if player.game.status == "finished"
        @closedgames << player.game
      elsif player.game.status == "open"
        @opengames << player.game
      end
    end
    
  end

  def show
    @game = Game.find(params[:id])
    if current_user
      @player = Player.where(user_id: current_user.id, game: @game).first
    else
      @player = Player.new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def create
    @game = Game.new(game_params)
    @game.gamemaster = current_user
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @game = Game.new
  end
  
  def gamemaster
    @opengames = Game.where(gamemaster: current_user, status: "open") + Game.where(gamemaster: current_user, status: "running")
    @closedgames = Game.where(gamemaster: current_user, status: "finished")
  end
  
  def participate
    game = Game.find(params[:id])
    if current_user
     if game.participate(current_user)
       redirect_to game, notice: "Erfolgreich für das Spiel #{game.name} angemeldet"
     else
       redirect_to game, :flash => {error: "Anmeldung nicht möglich! 
       Es wurde die E-Mail-Adresse oder der Name schonmal für dieses Spiel verwendet"}
     end
    else
     if game.participate(nil, params[:name], params[:email])
       redirect_to game, notice: "Erfolgreich für das Spiel #{game.name} angemeldet"
     else
       redirect_to game, :flash => {error: "Anmeldung nicht möglich! 
       Es wurde die E-Mail-Adresse oder der Name schonmal für dieses Spiel verwendet"}
     end
    end
  end
  
  def kill
    game = Game.find(params[:id])
    if current_user
      job = Job.where(killer_id: params[:killer], victim_id: params[:victim],status: "unfinished").first
      if job
        job.kill(params[:plot], params[:date])
      else
        redirect_to game, :flash =>{error: "kein Passernder Auftrag gefunden"}
      end
    else
      job = Job.where(key: params[:key], victim: params[:victim],status: "unfinished").first
      if job
        job.kill(params[:plot])
      else
        redirect_to game, :flash =>{error: "kein Passernder Auftrag gefunden"}
      end
    end
    if game.jobs.where(status: "unfinished").empty?
      game.end
      redirect_to game, notice: "Dies war der letzte Auftrag das Spiel ist beendet"
    else
      redirect_to game, notice: "Mord Erfolgreich gemeldet"
    end
  end
  
  def start
    game = Game.find(params[:id])
    if game.start
      redirect_to game, notice: "Spiel Erfolgreich gestartet! Möge das Morden Beginnen"
    else
      redirect_to game, :flash =>{error: "konnte das Spiel nicht starten"}
    end
  end
  
  def end_game
    game = Game.find(params[:id])
    if game.end_game
      redirect_to game, notice: "Spiel Erfolgreich gestartet! Möge das Morden Beginnen"
    else
      redirect_to game, :flash =>{error: "konnte das Spiel nicht starten"}
    end
  end
  
  private
  def game_params
    params[:game].permit(:name, :circle_count, :tweet, :starttime, :endtime)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_gmshow.html.haml
%h1{'style' => 'display: inline-block'}
  = @game.name 
  (
  =t @game.status
  )
.pull-right
  -if @game.status == "open"
    =link_to "Spiel starten", start_game_path(@game), class: 'btn btn-primary'
  -elsif @game.status == "running"
    =link_to "Spiel Beenden", end_game_path(@game), class: 'btn btn-danger'
.row-fluid
  .span6
    %table.table
      %thead
        %tr
          %th Mitspieler
      - @game.player.sort_by{|e| e.get_name}.each do |player|
        %tr
          %td= player.get_name
  .span6
    -if @game.status == "running" || @game.status == "finished"
      -@game.circles.each do |circle|
        .accordion{id: "accordion_circles#{circle.number}"}
          .accordion-group
            .accordion-heading.center
              = link_to "Aufträge Kreis: #{circle.number}", "#collapse_#{circle.number}", class: 'accordion-toggle', data: {toggle: "collapse", parent: "#accordion_circles#{circle.number}"}
            .accordion-body.collapse{ id: "collapse_#{circle.number}"}
              .accordion-inner
                %table.table
                  %thead
                    %tr
                      %th Mörder
                      %th Opfer
                      %th Tathergang
                      %th Zeitpunkt
                      %th Status
                    -circle.jobs.each do |job|
                      %tr
                        %td=job.killer
                        %td=job.victim
                        %td=job.plot
                        -if job.status == "done"
                          %td=l job.time, format: :short
                        -else
                          %td
                        %td=t job.status

app/views/games/_ushow.html.haml
%h1{'style' => 'display: inline-block'}
  = @game.name 
-if current_user && @game.gamemaster == current_user
  =link_to "Spiel starten", start_game_path(@game), class: 'btn btn-primary'
.row-fluid
  .span6
    %table.table
      %thead
        %tr
          %th Mitspieler
      - @game.player.sort_by{|e| e.get_name}.each do |player|
        %tr
          %td= player.get_name
  .span6
    -if @game.status == "open"
      -if current_user 
        -if(current_user != @game.gamemaster)
          =link_to "An Spiel als #{current_user.username} teilnehmen", participate_path(@game)
      -else
        = form_tag(participate_path(@game), method: "get") do
          = label_tag(:name, "Nutzername")
          = text_field_tag(:name)
          = label_tag(:email, "Email-Adresse")
          = text_field_tag(:email)
          %br
          = submit_tag("Teilnehmen")
    -elsif @game.status == "running"
      -if current_user
        = form_tag(kill_path(@game), method: "get") do
          - if @player.has_multi_kill?
            = select_tag "victim", options_from_collection_for_select(@game.circles, "id", "number"), include_blank: true
          = hidden_field_tag :killer, @player.id
          = label_tag(:name, "Opfer")
          = select_tag "victim", options_from_collection_for_select(@game.player, "id", "get_name"), include_blank: true
          = label_tag(:plot, "Tathergang")
          = text_field_tag(:plot)
          .date
            = label_tag(:time, "Todeszeit")
            = select_datetime(Time.new, order: [:day, :month, :year])
          %br
          = submit_tag("Mord melden")    
      -else
        = form_tag(kill_path(@game), method: "get") do
          = label_tag(:key, "Auftragscode")
          = text_field_tag(:key)
          = label_tag(:name, "Opfer")
          = select_tag "victim", options_from_collection_for_select(@game.player, "id", "get_name"), include_blank: true
          = label_tag(:plot, "Tathergang")
          = text_field_tag(:plot)
          = label_tag(:time, "Toteszeit")
          .date
            = label_tag(:time, "Todeszeit")
            = select_datetime(Time.local, order: [:day, :month, :year])
          %br
          = submit_tag("Mord melden") 
          
.row-fluid
  .span12
    %h4 Morde
    %table.table
      %thead
        %tr
          %th Kreis
          %th Mörder
          %th Opfer
          %th Tathergang
          %th Zeitpunkt
      -@game.finished_jobs.each do |job|
        %tr
          %td=job.circle.number
          %td=job.killer
          %td=job.victim
          %td=job.plot
          -if job.status == "done"
            %td=l job.time, format: :short
         

app/views/games/edit.html.haml
%h1 Games#edit
%p Find me in app/views/games/edit.html.haml

app/views/games/gamemaster.html.haml
%h1 Spiele

%h3 Offene Spiele

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th Name
      %th Anzahl Spieler
      %th Start
      %th Ende
  - @opengames.each do |game|
    %tr
      %td=link_to game.name, game
      %td=game.get_player_statistics
      %td=l game.starttime, format: :short
      %td=l game.endtime, format: :short
%h3 Beendete Spiele

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th Name
      %th Anzahl Spieler
      %th Ende
  - @closedgames.each do |game|
    %tr
      %td=link_to game.name, game
      %td=game.get_player_statistics
      %td=l game.endtime, format: :short

app/views/games/index.html.haml
%h1 Spiele

%h3 Offene Spiele

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th Name
      %th Anzahl Spieler
      %th Start
      %th Ende
      %th Spielleiter
  - @opengames.each do |game|
    %tr
      %td=link_to game.name, game
      %td=game.get_player_statistics
      %td=l game.starttime, format: :short
      %td=l game.endtime, format: :short
      %td=game.gamemaster.username
%h3 Beendete Spiele

%table.table.table-condensed.table-hover
  %thead
    %tr
      %th Name
      %th Anzahl Spieler
      %th Start
      %th Ende
      %th Spielleiter
  - @closedgames.each do |game|
    %tr
      %td=link_to game.name, game
      %td=game.get_player_statistics
      %td=l game.starttime, format: :short
      %td=l game.endtime, format: :short
      %td=game.gamemaster.username

app/views/games/new.html.haml
%h1 Neues Spiel Erstellen
= form_for(@game) do |f|
  - if @game.errors.any?
    #error_explanation
      %h2
        = pluralize(@game.errors.count, "error")
        prohibited this user from being saved:
      %ul
        - @game.errors.full_messages.each do |msg|
          %li= msg
  = f.label :Spielname
  = f.text_field :name
  .date
    = f.label :Start
    = f.datetime_select "starttime"
    = f.label :Ende
    = f.datetime_select "endtime"
  .circles
    =f.label :Kreise
    =f.number_field "circle_count", min: 1
  =hidden_field :gamemaster, value: current_user
  =hidden_field :status, value: "open"
  =f.label :Tweeten?
  =f.check_box "tweet"
  .actions
    = f.submit "Abschicken"

app/views/games/show.html.haml
-if current_user && @game.gamemaster == current_user
  =render 'gmshow'
-else
  =render 'ushow'