config/routes.rb
Moerderspiel::Application.routes.draw do
  resources :rankings

  resources :users
  resources :games
  resources :sessions
  resources :password_resets

  get "login"   => "sessions#new",        :as => "login"
  get "logout"  => "sessions#destroy",    :as => "logout"
  get "signup"  => "users#new",           :as => "signup"
  get "gamemaster" => "games#gamemaster", :as => "gamemaster"
  get "participate/:id" => "games#participate", :as => "participate"
  get "ranking" => "rankings#index", :as => "user_ranking"
  get "kill/:id" => "games#kill", :as => "kill"
  get "start/:id" => "games#start", :as => "start_game"
  get "end/:id" => "games#end_game", :as => "end_game"

  root 'welcome#index'
  get 'welcome/show_game_by_name'

end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Mörderspiel"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'

  .span10.offset1
    %body
      .navbar.navbar-fluid-top
        .navbar-inner
          .container-fluid
            %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            = link_to "Mörderspiel", root_path, { class: :brand }
            .container.nav-collapse
              %ul.nav
                - if current_user
                  %li= link_to "Spiele", games_path
                  %li= link_to "Meine Spiele", gamemaster_path
                  %li= link_to "Rangliste", user_ranking_path
              .pull-right
                -if policy(Game).create?
                  %ul.nav
                    %li=link_to "#{current_user.username}", edit_user_path(current_user)
                    %li=link_to "Abmelden", logout_path
                -else
                  %ul.nav
                    %li=link_to "Anmelden", login_path
                    %li=link_to "Registrieren", new_user_path

      .container-fluid
        .span9
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Stuga Informatik 2013
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"